"""Run 34686824352 automatic-topic CANDIDATE_POOL scope leak regression.

Authority: production Run 34686824352 (automatic-topic mode, blank
`SHORTS_TOPIC` and blank `SHORTS_CANDIDATE_SCOPE`) exhausted all 7 Candidate
attempts -- 5 of 7 returned a `CANDIDATE_POOL` envelope and were REGENERATEd
with `이유: CANDIDATE_POOL response received outside aviation scope`, only 2
attempts even reached a real topic (both then correctly REGENERATEd by the
ordinary Candidate Gate, unrelated to this bug).

Root cause: `CANDIDATE_EXPLORER_PROMPT`'s section 15 ("AVIATION CANDIDATE POOL
HANDOFF V1") is appended unconditionally at import time, so the model sees
that output contract on every call regardless of the runtime
`SHORTS_CANDIDATE_SCOPE`, and does not reliably self-gate on the in-prompt
"When SHORTS_CANDIDATE_SCOPE=aviation" instruction alone.

Fix: keep CANDIDATE_POOL parsing/validation exactly aviation-only (no
fail-open, no change to Candidate Gate, no aviation-only validation applied to
general topics) -- only stop teaching the model that output shape for a call
that cannot use it, by removing section 15 from the system prompt for the
duration of a non-aviation-scope call and restoring it immediately after.

This regression composes the real production hotfix chain in a scratch copy
and proves cases A-F.
"""
from __future__ import annotations

import importlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

_CHAIN = [
    "ci_hotfix.py", "ci_novelty_budget_hotfix.py", "ci_fact_critical_hotfix.py",
    "ci_speech_style_hotfix.py", "ci_hook_generation_hotfix.py", "ci_hook_pool_guard_hotfix.py",
    "ci_retention_hotfix.py", "ci_first5_retention_tts_hotfix.py", "ci_first5_visual_contract_hotfix.py",
    "ci_video_provider_hotfix.py", "ci_topic_input_hotfix.py", "ci_aviation_candidate_context_hotfix.py",
    "ci_aviation_candidate_specificity_hotfix.py", "ci_aviation_context_signature_compat_hotfix.py",
    "ci_aviation_specificity_output_repair_hotfix.py", "ci_aviation_specificity_projection_hotfix.py",
    "ci_candidate_grounded_recovery_hotfix.py", "ci_growth_candidate_shadow_hotfix.py",
    "ci_final_render_content_integrity_hotfix.py", "ci_output_quality_hotfix.py",
    "ci_curiosity_retention_hotfix.py", "ci_visual_specificity_hotfix.py", "ci_design_causality_hotfix.py",
    "ci_query_semantic_integrity_hotfix.py", "ci_concrete_visual_evidence_hotfix.py",
    "ci_visible_evidence_provenance_hotfix.py", "ci_hook_production_parity_hotfix.py",
    "ci_hook_fallback_quality_floor_hotfix.py", "ci_ai_visual_fallback_hotfix.py",
    "ci_ai_visual_mechanism_fallback_hotfix.py", "ci_problem_solution_narrative_hotfix.py",
    "ci_causal_information_progression_hotfix.py", "ci_retention_structure_experiment_hotfix.py",
    "ci_subscriber_conversion_hotfix.py", "ci_script_production_parity_hotfix.py",
    "ci_script_production_parity_bridge_hotfix.py", "ci_adaptive_scene_count_hotfix.py",
    "ci_general_scene_visual_parity_hotfix.py", "ci_script_validation_recovery_hotfix.py",
    "ci_script_v2_visual_goal_hotfix.py", "ci_script_v2_gunggeum_formal_ending_hotfix.py",
    "ci_final_visual_semantic_qa_hotfix.py", "ci_cross_process_video_dedupe_hotfix.py",
    "ci_writer_observable_opening_hotfix.py", "ci_grounded_deterministic_explanation_hotfix.py",
    "ci_aviation_context_signature_compat_hotfix.py",
]


def _prepare_repo() -> Path:
    scratch = Path(tempfile.mkdtemp(prefix="run_34686824352_"))
    repo = scratch / "repo"
    shutil.copytree(ROOT, repo, ignore=shutil.ignore_patterns(".git", "__pycache__", "*.pyc"))
    for script in _CHAIN:
        result = subprocess.run(
            [sys.executable, script],
            cwd=repo,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise AssertionError(
                f"production composition failed at {script}\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
            )
    return repo


def main():
    repo = _prepare_repo()
    try:
        source = (repo / "ci_candidate_pool_handoff_hotfix.py").read_text(encoding="utf-8")
        assert "RUN_34686824352_AVIATION_PROMPT_SCOPE_V1" in source
        composed = (repo / "content/candidate_explorer.py").read_text(encoding="utf-8")
        assert "RUN_34686824352_AVIATION_PROMPT_SCOPE_V1" in composed

        sys.path.insert(0, str(repo))
        try:
            for name in list(sys.modules):
                if name == "content" or name.startswith("content."):
                    del sys.modules[name]
            ce = importlib.import_module("content.candidate_explorer")
            legacy = ce._LEGACY

            baseline_prompt = legacy.CANDIDATE_EXPLORER_PROMPT
            assert "AVIATION CANDIDATE POOL HANDOFF" in baseline_prompt

            captured = {}

            def spy(*args, **kwargs):
                captured["prompt"] = legacy.CANDIDATE_EXPLORER_PROMPT
                captured["args"] = args
                captured["kwargs"] = kwargs
                return {"status": "REGENERATE", "reason": "stub"}

            real_previous = legacy._candidate_pool_scope_previous_explore_candidates

            # CASE A: automatic (blank scope) call -> the model is no longer
            # shown the CANDIDATE_POOL contract at all, so a real response
            # follows the ordinary SELECTED/REGENERATE parse path (the actual
            # non-leak assertion is the prompt content itself).
            import os

            os.environ["SHORTS_CANDIDATE_SCOPE"] = ""
            legacy._candidate_pool_scope_previous_explore_candidates = spy
            try:
                legacy.explore_candidates(
                    {"category": "자동 탐색", "topic": "일상 속 과학 원리"},
                    recent_topics=[],
                )
            finally:
                legacy._candidate_pool_scope_previous_explore_candidates = real_previous
            assert "AVIATION CANDIDATE POOL HANDOFF" not in captured["prompt"], (
                "section 15 leaked into a non-aviation automatic call"
            )
            assert legacy.CANDIDATE_EXPLORER_PROMPT == baseline_prompt, (
                "global prompt must be restored after a non-aviation call"
            )
            print("CASE A automatic + non-aviation call no longer sees CANDIDATE_POOL contract: PASS")

            # CASE B: automatic + aviation scope keeps the existing aviation
            # contract completely unchanged.
            os.environ["SHORTS_CANDIDATE_SCOPE"] = "aviation"
            captured.clear()
            legacy._candidate_pool_scope_previous_explore_candidates = spy
            try:
                legacy.explore_candidates(
                    {"category": "지정 주제", "topic": "비행기 창문 모서리는 왜 둥글까"},
                    recent_topics=[],
                    fixed_topic="비행기 창문 모서리는 왜 둥글까",
                    fixed_topic_gate_feedback="",
                )
            finally:
                legacy._candidate_pool_scope_previous_explore_candidates = real_previous
            assert "AVIATION CANDIDATE POOL HANDOFF" in captured["prompt"], (
                "aviation scope must keep the existing CANDIDATE_POOL contract"
            )
            assert legacy.CANDIDATE_EXPLORER_PROMPT == baseline_prompt
            print("CASE B automatic + aviation keeps existing contract: PASS")

            # CASE C: fixed aviation topic (the exact Run #531 success shape)
            # is byte-identical in prompt content -- no regression to that
            # landed success path.
            os.environ["SHORTS_CANDIDATE_SCOPE"] = "aviation"
            captured.clear()
            legacy._candidate_pool_scope_previous_explore_candidates = spy
            try:
                legacy.explore_candidates(
                    {"category": "지정 주제", "topic": "비행기 창문 모서리는 왜 둥글까"},
                    recent_topics=[],
                    fixed_topic="비행기 창문 모서리는 왜 둥글까",
                    fixed_topic_gate_feedback="직전 이유",
                )
            finally:
                legacy._candidate_pool_scope_previous_explore_candidates = real_previous
            assert captured["prompt"] == baseline_prompt, (
                "Run #531 fixed-topic aviation path prompt must be byte-identical"
            )
            assert captured["kwargs"].get("fixed_topic_gate_feedback") == "직전 이유", (
                "Run 34685288234 gate-feedback forwarding must still work"
            )
            print("CASE C fixed-topic aviation path (#531) unaffected: PASS")

            # CASE D: a malformed/CANDIDATE_POOL envelope arriving outside
            # aviation scope anyway must still fail closed, never fail-open.
            os.environ["SHORTS_CANDIDATE_SCOPE"] = ""
            result = legacy.validate_explorer_output(
                {"status": "CANDIDATE_POOL", "candidates": [{"topic": "x"}]}
            )
            assert result.get("status") == "REGENERATE"
            assert "outside aviation scope" in result.get("reason", "")
            print("CASE D malformed CANDIDATE_POOL outside aviation scope fails closed: PASS")

            # CASE E: an explicitly-set non-aviation scope value (not just
            # blank) behaves identically to blank -- scope authority stays
            # exactly the existing single "== aviation" gate.
            os.environ["SHORTS_CANDIDATE_SCOPE"] = "urban"
            captured.clear()
            legacy._candidate_pool_scope_previous_explore_candidates = spy
            try:
                legacy.explore_candidates(
                    {"category": "자동 탐색", "topic": "도시 인프라"},
                    recent_topics=[],
                )
            finally:
                legacy._candidate_pool_scope_previous_explore_candidates = real_previous
            assert "AVIATION CANDIDATE POOL HANDOFF" not in captured["prompt"]
            result2 = legacy.validate_explorer_output({"status": "CANDIDATE_POOL", "candidates": []})
            assert result2.get("status") == "REGENERATE"
            print("CASE E explicit non-aviation scope value behaves like blank: PASS")

        finally:
            sys.path.remove(str(repo))
            del os.environ["SHORTS_CANDIDATE_SCOPE"]

        # CASE F: no budget/floor/retry/model-routing constant touched.
        for forbidden in (
            "V3_MAX_COST_USD =",
            "V3_MAX_API_CALLS =",
            "MAX_TOPIC_REGENERATIONS =",
            "HOOK_MIN_SCORE =",
            "MAX_EXPLANATION_TRANSFORMS_PER_VIDEO",
            "temperature=0.",
            "AI_MAX_GENERATIONS_PER_VIDEO",
        ):
            assert forbidden not in source, forbidden
        print("CASE F budgets/floors/retries/model routing unchanged: PASS")

        print("RUN 34686824352 AUTOMATIC TOPIC CANDIDATE_POOL SCOPE REGRESSION: PASS")
    finally:
        shutil.rmtree(repo.parent, ignore_errors=True)


if __name__ == "__main__":
    main()
