name: Shorts Creator Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-nanum

      - name: Create Venv and Install Packages
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install edge-tts openai requests moviepy==1.0.3 Pillow==9.5.0 numpy google-api-python-client google-auth-oauthlib google-auth-httplib2

      - name: Run Shorts Creator Script
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          ./venv/bin/python main.py
