name: Shorts Creator Bot

on:
  workflow_dispatch: # [수동 실행] 버튼 유지
  schedule:
    # ⏰ 매일 정해진 시간에 자동 실행 (UTC 기준 / 한국 시간 = UTC + 9시간)
    # 1. 매일 아침 8시 (UTC 기준 전날 23:00)
    - cron: '0 23 * * *'
    # 2. 매일 저녁 6시 (UTC 기준 당일 09:00)
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick fonts-nanum
          sudo sed -i 's/<policy domain="path" rights="none" pattern="@\*" \/>/<policy domain="path" rights="read|write" pattern="@\*" \/>/g' /etc/ImageMagick-6/policy.xml


      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Shorts Creator Script
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py
